# Álgebra Linear Computacional - CKP8122 - MDCC - UFC
### Francisco Mateus dos Anjos Silva
# Método de Householder

In [1]:
# Implementar o método de Householder e faça o que se pede:

# 1) imprima a matriz original (teste matrizes nxn com n > 6,  simétricas e não simétricas);

# 2) em cada passo,  imprima a matriz de householder, a matriz modificada pela transformação de similaridade, 
#    e a matriz de householder acumulada;

# 3) no final do loop de execução  imprima: 
#    -  a matriz de saída (Tridiagonal se a matriz de entrada for simétrica, 
#       ou Upper-Hessemberg se a matriz de entrada não for simétrica);
#    -  a matriz de Householder acumulada (final).

Em álgebra linear, uma **transformação de Householder** (também conhecida como uma reflexão de Householder ou refletor elementar) é uma transformação linear que descreve uma reflexão em relação a um plano ou hiperplano que contém a origem. A transformação de Householder foi introduzida em 1958 por Alston Scott Householder. 
O seu análogo em espaços com produto interno mais gerais é o operador de Householder.

**Transformação**

O hiperplano de reflexão pode ser definido por um vetor unitário ${\textstyle v}$ (um vetor de comprimento ${\textstyle 1}$) que é ortogonal ao plano. A reflexão de um ponto ${\textstyle x}$ em relação a este hiperplano é a transformação linear:

${\displaystyle x-2\langle x,v\rangle v=x-2v\left(v^{\textsf {H}}x\right),}$ em que ${\textstyle v}$ é dado como um vetor coluna unitário com conjugado transposto ${\textstyle v^{\textsf {H}}.}$

**Matriz de Householder**

A matriz construída a partir dessa transformação pode ser expressa em termos de um produto externo como:

${\displaystyle P=I-2(v\otimes v)=I-2vv^{\textsf {H}}}$

é conhecida como a matriz de Householder, em que ${\textstyle I}$ é a matriz de identidade.

**Propriedades**

A matriz de Householder tem as seguintes propriedades:

- é Hermitiana: ${\textstyle P=P^{\textsf {H}},}$
- é unitária: ${\textstyle P^{-1}=P^{\textsf {H}},}$
- consequentemente, é involutiva: ${\textstyle P^{2}=I.}$
- Uma matriz de Householder tem autovalores ${\textstyle \pm 1.}$ Para ver isto, note que se ${\textstyle u}$ é ortogonal ao vetor ${\textstyle v}$ que foi utilizado para criar o refletor, então ${\textstyle Pu=u,}$ ou seja, ${\textstyle 1}$ é um autovalor de multiplicidade ${\textstyle n-1,}$ uma vez que existem ${\textstyle n-1}$ vetores linearmente independentes ortogonais a ${\textstyle v.}$ Além disso, observe que ${\textstyle Pv=-v}$ e assim ${\textstyle -1}$ é um autovalor com multiplicidade ${\textstyle 1.}$
- O determinante de um refletor de Householder é ${\textstyle -1,}$ uma vez que o determinante de uma matriz é o produto de seus autovalores e, neste caso, um deles é ${\textstyle -1}$ e o restante é ${\textstyle 1}$ (como no ponto anterior).

**Referências:**

- https://pt.wikipedia.org/wiki/Transforma%C3%A7%C3%A3o_de_Householder#:~:text=Em%20%C3%A1lgebra%20linear%2C%20uma%20transforma%C3%A7%C3%A3o,1958%20por%20Alston%20Scott%20Householder

In [2]:
import numpy as np
import math

In [3]:
def mount_householder_matrix(A, j):    
    A = A.astype(np.float32)
    n_A = len(A)
    v = np.zeros(n_A)
    w = np.zeros(n_A)
    v[j+1:] = A[j+1:,j]
    w[j+1] = np.linalg.norm(v)
    n = np.array([(v - w) / np.linalg.norm(v - w)])
    H = np.identity(n_A) - 2 * (n.T @ n)
    H = np.around(H, decimals=5)
    return H

In [4]:
def householder_method(A):
    print('Matriz original:\n', A)
    n_A = len(A)
    H_acc = np.identity(n_A)
    matrix = A.copy()
    
    for j in range(0, n_A - 2):
        Hj = mount_householder_matrix(matrix, j)
        print('\n\nMatriz de Householder ( passo', j, '):\n', Hj)

        matrix = np.around(Hj @ matrix @ Hj, decimals=4)
        print('\nMatriz modificada pela transformação de similaridade ( passo', j, '):\n', matrix)
        
        H_acc = np.around(H_acc @ Hj, decimals=4)
        print('\nMatriz de Householder acumulada ( passo', j, '):\n', H_acc)
    
    return matrix, H_acc

### Teste com Matriz Simétrica 

In [5]:
# Matriz 7x7
A = np.array([[3, 2, 1, 1, 2, 0, 2],
              [2, 3, 0, 2, 1, 0, 0],
              [1, 0, 2, 0, 2, 1, 1],
              [1, 2, 0, 3, 0, 0, 2],
              [2, 1, 2, 0, 3, 1, 0],
              [0, 0, 1, 0, 1, 1, 1],
              [2, 0, 1, 2, 0, 1, 1]])

matrix, H_acc = householder_method(A)

Matriz original:
 [[3 2 1 1 2 0 2]
 [2 3 0 2 1 0 0]
 [1 0 2 0 2 1 1]
 [1 2 0 3 0 0 2]
 [2 1 2 0 3 1 0]
 [0 0 1 0 1 1 1]
 [2 0 1 2 0 1 1]]


Matriz de Householder ( passo 0 ):
 [[ 1.       0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.53452  0.26726  0.26726  0.53452  0.       0.53452]
 [ 0.       0.26726  0.84655 -0.15345 -0.3069   0.      -0.3069 ]
 [ 0.       0.26726 -0.15345  0.84655 -0.3069   0.      -0.3069 ]
 [ 0.       0.53452 -0.3069  -0.3069   0.38619  0.      -0.61381]
 [ 0.       0.       0.       0.       0.       1.       0.     ]
 [ 0.       0.53452 -0.3069  -0.3069  -0.61381  0.       0.38619]]

Matriz modificada pela transformação de similaridade ( passo 0 ):
 [[ 3.      3.7416  0.      0.      0.      0.      0.    ]
 [ 3.7416  4.9285  0.8428  1.6446  0.082   1.3363 -1.2543]
 [ 0.      0.8428  0.3964 -0.9156  0.2877  0.2327 -0.5192]
 [ 0.      1.6446 -0.9156  2.7724 -0.3364 -0.7672  1.8567]
 [ 0.      0.082   0.2877 -0.3364  2.5651 -0.5345 -0.0487

### Teste com Matriz Não Simétrica 

In [6]:
# Matriz 7x7
A = np.array([[3, 2, 1, 1, 2, 0, 2],
              [1, 3, 0, 2, 1, 0, 0],
              [5, 0, 2, 0, 2, 1, 1],
              [1, 5, 0, 3, 0, 0, 2],
              [2, 1, 3, 5, 3, 1, 0],
              [3, 5, 1, 0, 2, 1, 1],
              [2, 0, 5, 2, 3, 0, 1]])
matrix, H_acc = householder_method(A)

Matriz original:
 [[3 2 1 1 2 0 2]
 [1 3 0 2 1 0 0]
 [5 0 2 0 2 1 1]
 [1 5 0 3 0 0 2]
 [2 1 3 5 3 1 0]
 [3 5 1 0 2 1 1]
 [2 0 5 2 3 0 1]]


Matriz de Householder ( passo 0 ):
 [[ 1.       0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.15076  0.75378  0.15076  0.30151  0.45227  0.30151]
 [ 0.       0.75378  0.33096 -0.13381 -0.26762 -0.40143 -0.26762]
 [ 0.       0.15076 -0.13381  0.97324 -0.05352 -0.08029 -0.05352]
 [ 0.       0.30151 -0.26762 -0.05352  0.89295 -0.16057 -0.10705]
 [ 0.       0.45227 -0.40143 -0.08029 -0.16057  0.75914 -0.16057]
 [ 0.       0.30151 -0.26762 -0.05352 -0.10705 -0.16057  0.89295]]

Matriz modificada pela transformação de similaridade ( passo 0 ):
 [[ 3.      2.4121  0.6342  0.9269  1.8537 -0.2195  1.8537]
 [ 6.6333  6.841   1.6453  2.3191  3.2812 -0.1285  0.7184]
 [-0.     -2.2709 -0.4706 -0.4852 -0.4289  0.5078 -0.0418]
 [-0.      0.7821  2.8466  3.5712  0.8505  1.906   3.1279]
 [-0.      2.4686 -0.098   4.384   1.1845 -0.4627 -1.2606