# Álgebra Linear Computacional - CKP8122 - MDCC - UFC
# Reduced Row Echelon Form (RREF)
### Francisco Mateus dos Anjos Silva

In [1]:
# Implemente o método para determinar o RREF de uma matriz mxn e, 
# testando em matrizes com m > n, m < n e m = n, determine:

# 1) RREF da matriz;
# 2) O posto da matriz (rank): quantidade de linhas não nulas;
# 3) A dimensão do espaço nulo da matriz: quantidade de linhas nulas.


In [2]:
import numpy as np
import sympy
import math

In [3]:
def eliminate_element_by_pivot(matrix, row=0, col=0):
    pivot = float(matrix[col][col])
    multiplicator = -(matrix[row][col]/pivot)
    matrix[row] = matrix[col].copy() * multiplicator + matrix[row].copy()
    return matrix

In [4]:
def get_next_index_row_pivot_not_zero(A, column_index):
    for i in range(column_index, len(A)):
        if A[i][column_index] != 0:
            return i
    return None

In [5]:
# Calcula a RREF de uma matriz

def rref(A):
    # Número de linhas 
    n = len(A)
    # Número de colunas
    m = len(A[0])
    rref = A.copy()

    for i in range(0, m):
        if i >= n:
            break
            
        pivot = float(rref[i][i])
        if pivot == 0:
            # Permutação de Linha
            index_row_pivot_not_zero = get_next_index_row_pivot_not_zero(rref, i)            
            if not index_row_pivot_not_zero:
                # Não encontrado outro possível pivo na coluna i
                continue            
            # Permutando linhas
            rref[i], rref[index_row_pivot_not_zero] = rref[index_row_pivot_not_zero].copy(), rref[i].copy()       
            pivot = rref[i][i]            
                
        # Se o pivo não for 1, divide pelo seu valor para que fique 1
        if pivot != 1:
            rref[i] = np.true_divide(rref[i].copy(), pivot)          
        
        # Elimina (zera) os outros valores naquela coluna
        for j in range(0, n):
            if j != i:
                rref = eliminate_element_by_pivot(rref, row=j, col=i)
                rref = np.around(rref,decimals=3)
    
    zeros_row = np.zeros(m)
    # Permuta as linhas com valores zero para as últimas linhas
    for j in range(0, n):
        if (rref[j] == zeros_row).all():            
            rref[j], rref[n-1] = rref[n-1].copy(), rref[j].copy()       
            
    return rref

In [6]:
# Encontra as colunas com pivôs de uma matriz

def pivot_colums(A):
    pivots = []
    # Utiliza a RREF para encontrar as colunas pivot
    RREF = rref(A)
    n = len(RREF)
    m = len(RREF[0])
    pivot_index = 0
    
    for i in range(0, n):
        if pivot_index >= m:
            break
            
        pivot = 0
        # Percorre as colunas procurando um valor diferente de zero
        while pivot == 0 and pivot_index < m:
            pivot = RREF[i][pivot_index]
            if pivot != 0:
                pivots.append(pivot_index)
            pivot_index+=1
            
    return pivots

In [7]:
# Calcula o posto (rank) de uma matriz

def rank(A):
    return len(pivot_colums(A))

In [8]:
# Teste com dados 1: 5x4
A = np.array([[1, 2, 3, 4],
              [4, 5, 6, 7],
              [6, 7, 8, 9],
              [5, 7, 8, 9],
              [9, 7, 8, 9]])

A = A.astype(np.float32)

num_colunas = A.shape[1]

print("Matriz A:\n", A)

RREF = rref(A)
print("\nRREF da matriz:\n", RREF)
print("Sympy RREF: \n {}".format(sympy.Matrix(A).rref()[0]))

rank_result = rank(A)
print("\nRank da matriz:", rank_result)
print("Sympy Rank", sympy.Matrix(A).rank())

print("\nDimensão do espaço nulo da matriz:", (num_colunas-rank_result))
print("Dimensão pelo Sympy:", len(sympy.Matrix(A).nullspace()))

Matriz A:
 [[1. 2. 3. 4.]
 [4. 5. 6. 7.]
 [6. 7. 8. 9.]
 [5. 7. 8. 9.]
 [9. 7. 8. 9.]]

RREF da matriz:
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0. -1.]
 [-0. -0.  1.  2.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
Sympy RREF: 
 Matrix([[1, 0, 0, 0], [0, 1, 0, -1.00000], [0, 0, 1, 2.00000], [0, 0, 0, 0], [0, 0, 0, 0]])

Rank da matriz: 3
Sympy Rank 3

Dimensão do espaço nulo da matriz: 1
Dimensão pelo Sympy: 1


In [9]:
# Teste com dados 2: 3x4
A = np.array([[1, 2, 3, 4],
              [4, 5, 6, 7],
              [6, 7, 8, 9]])

A = A.astype(np.float32)

num_colunas = A.shape[1]

print("Matriz A:\n", A)

RREF = rref(A)
print("\nRREF da matriz:\n", RREF)
print("Sympy RREF: \n {}".format(sympy.Matrix(A).rref()[0]))

rank_result = rank(A)
print("\nRank da matriz:", rank_result)
print("Sympy Rank", sympy.Matrix(A).rank())

print("\nDimensão do espaço nulo da matriz:", (num_colunas-rank_result))
print("Dimensão pelo Sympy:", len(sympy.Matrix(A).nullspace()))


Matriz A:
 [[1. 2. 3. 4.]
 [4. 5. 6. 7.]
 [6. 7. 8. 9.]]

RREF da matriz:
 [[ 1.  0. -1. -2.]
 [-0.  1.  2.  3.]
 [ 0.  0.  0.  0.]]
Sympy RREF: 
 Matrix([[1, 0, -1.00000, -2.00000], [0, 1, 2.00000, 3.00000], [0, 0, 0, 0]])

Rank da matriz: 2
Sympy Rank 2

Dimensão do espaço nulo da matriz: 2
Dimensão pelo Sympy: 2


In [10]:
# Teste com dados 3: 10x10
A = np.array([[1,2,3,4,5,6,7,8,9,10],
      [10,2,2,3,4,5,6,7,8,9],
      [9,10,1,2,3,4,5,6,7,8],
      [8,9,10,1,2,3,4,5,6,7],
      [7,8,9,10,1,2,3,4,5,6],
      [6,7,8,9,10,1,2,3,4,5],
      [5,6,7,8,9,10,1,2,3,4],
      [4,5,6,7,8,9,10,1,2,3],
      [3,4,5,6,7,8,9,10,1,2],
      [2,3,4,5,6,7,8,9,10,2]])

A = A.astype(np.float32)

num_colunas = A.shape[1]

print("Matriz A:\n", A)

RREF = rref(A)
print("\nRREF da matriz:\n", RREF)
print("Sympy RREF: \n {}".format(sympy.Matrix(A).rref()[0]))

rank_result = rank(A)
print("\nRank da matriz:", rank_result)
print("Sympy Rank", sympy.Matrix(A).rank())

print("\nDimensão do espaço nulo da matriz:", (num_colunas-rank_result))
print("Dimensão pelo Sympy:", len(sympy.Matrix(A).nullspace()))


Matriz A:
 [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
 [10.  2.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 9. 10.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 8.  9. 10.  1.  2.  3.  4.  5.  6.  7.]
 [ 7.  8.  9. 10.  1.  2.  3.  4.  5.  6.]
 [ 6.  7.  8.  9. 10.  1.  2.  3.  4.  5.]
 [ 5.  6.  7.  8.  9. 10.  1.  2.  3.  4.]
 [ 4.  5.  6.  7.  8.  9. 10.  1.  2.  3.]
 [ 3.  4.  5.  6.  7.  8.  9. 10.  1.  2.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.  2.]]

RREF da matriz:
 [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [-0. -0. -0. -0. -0. -0. -0. -0. -0.  1.]]
Sympy RREF: 
 Matrix([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0