# Álgebra Linear Computacional - CKP8122 - MDCC - UFC
### Francisco Mateus dos Anjos Silva
# Decomposição QR

In [1]:
# Implementar a decomposição QR de uma matriz nxn.

# 1) Entrar com uma matriz qualquer, A nxn
# 2) Encontrar as matrizes Q (ortogonal) e R (triangular superior) tal que A = Q R
# 3) imprimir as matrizes Q e R e mostrar que o produto QR = A.

Em álgebra linear, uma **decomposição QR** (também chamada de fatoração QR) de uma matriz é uma decomposição de uma matriz A em um produto A = QR de uma matriz ortogonal Q e uma matriz triangular superior R. A decomposição QR é usado frequentemente para resolver o problema de mínimos quadrados linear e é a base para um determinado algoritmo de autovalores, o algoritmo QR.

Matriz quadrada
Toda matriz quadrada A com entradas reais pode ser decomposta como

${\displaystyle A=QR,}$

em que Q é uma matriz ortogonal (suas colunas são vetores unitários ortogonais, isto é ${\displaystyle Q^{\textsf {T}}Q=QQ^{\textsf {T}}=I})$ e R é uma matriz triangular superior (também chamada de matriz triangular à direita). Se A é invertível, então a fatoração é única, se for exigido que os elementos da diagonal de R sejam positivos.

Se em vez disso A for uma matriz quadrada complexa, então há uma decomposição A = QR, em que Q é uma matriz unitária (então ${\displaystyle Q^{*}Q=QQ^{*}=I}$).

Se A tem n colunas linearmente independentes então as primeiras n colunas de Q formam uma base ortonormal para o espaço coluna de A. Mais geralmente, as primeiras k colunas de Q formam uma base ortonormal para o espaço gerado pelas primeiras k colunas de A para qualquer 1 ≤ k ≤ n. O fato de qualquer coluna k de A só depender das primeiras k colunas de Q é responsável pela forma triangular de R.

Existem vários métodos para calcular a decomposição QR, tais como o uso do processo de Gram–Schmidt, transformações Householder, ou rotações de Givens. Cada um tem suas vantagens e desvantagens. Mas vamos abordar apenas o método de decomposição QR que utiliza a transformação de Householder.

Uma **transformaçao de Householder** (ou reflexão de Householder) é uma transformação que pega um vetor e reflete-o em relação a algum plano ou hiperplano. Pode-se utilizar esta operação para calcular a fatoração QR de uma matriz ${\displaystyle A}$ de ordem m-por-n com m ≥ n.

Q pode ser utilizada para refletir um vetor de tal forma que todas as coordenadas exceto uma desapareçam.

Seja ${\displaystyle \mathbf {x} }$ ser um vetor coluna real arbitrário de ${\displaystyle A}$ de dimensão m, tal que ${\displaystyle \|\mathbf {x} \|=|\alpha |}$ para algum escalar α. Se o algoritmo é implementado usando a aritmética de ponto flutuante, então α deve receber o sinal contrário ao da k-ésima coordenada de ${\displaystyle \mathbf {x} ,}$ onde ${\displaystyle x_{k}}$ deve ser a coordenada pivô a partir da qual todas as entradas são 0 na forma triangular superior final de ${\displaystyle A}$, para evitar a perda de significância. No caso complexo, define-se

${\displaystyle \alpha =-e^{i\arg x_{k}}\|\mathbf {x} \|}$

(Stoer & Bulirsch 2002, p. 225) e substitui-se a transposição, pela transposição seguida de conjugação para a construção de Q como abaixo.

Então, sendo ${\displaystyle \mathbf {e}_{1}}$ o vetor (1 0 ... 0)T, ||·|| a norma Euclidiana e ${\displaystyle I}$ uma matriz identidade de ordem m-por-m, define-se

${\displaystyle {\begin{aligned}\mathbf {u} &=\mathbf {x} -\alpha \mathbf {e} _{1},\\\mathbf {v} &={\mathbf {u}  \over \|\mathbf {u} \|},\\Q&=I-2\mathbf {v} \mathbf {v} ^{\textsf {T}}.\end{aligned}}}$

Ou, se ${\displaystyle A}$ é complexo

${\displaystyle Q=I-2\mathbf {v} \mathbf {v} ^{*}}$. 

${\displaystyle Q}$ é uma matriz de Householder de ordem m-por-m e

${\displaystyle Q\mathbf {x} ={\begin{pmatrix}\alpha &0&\cdots &0\end{pmatrix}}^{\textsf {T}}.}$

Isso pode ser usado para transformar gradativamente uma matriz A de ordem m-por-n em uma matriz na forma triangular superior. Primeiramente, multiplica-se A pela matriz de Householder $Q_1$ que é obtida ao escolher a primeira matriz coluna para x. Isso resulta em uma matriz $Q_1 A$ com zeros na coluna da esquerda (exceto na primeira linha).

${\displaystyle Q_{1}A={\begin{bmatrix}\alpha _{1}&\star &\dots &\star \\0&&&\\\vdots &&A'&\\0&&&\end{bmatrix}}}$

Este processo pode ser repetido para A' (obtida a partir de $Q_1 A$ ao excluir a primeira linha e a primeira coluna), resultando em uma matriz de Householder $Q'_2$. Note que $Q'_2$ é menor do que $Q_1$. Como a intenção é fazer com que ela atue em $Q_1 A$ em vez de A' é preciso expandi-la para o canto superior esquerdo, preenchendo-a com 1, ou em geral:

${\displaystyle Q_{k}={\begin{pmatrix}I_{k-1}&0\\0&Q_{k}'\end{pmatrix}}.}$
Depois de ${\displaystyle t}$ iterações do processo, ${\displaystyle t=\min(m-1,n),}$

${\displaystyle R=Q_{t}\cdots Q_{2}Q_{1}A}$ é uma matriz triangular superior. Assim, com

${\displaystyle Q=Q_{1}^{\textsf {T}}Q_{2}^{\textsf {T}}\cdots Q_{t}^{\textsf {T}},}$ 
${\displaystyle A=QR}{\displaystyle A=QR}$ é uma decomposição QR de ${\displaystyle A.}$


**Referências:**

- https://pt.wikipedia.org/wiki/Decomposi%C3%A7%C3%A3o_QR

In [2]:
import numpy as np

In [3]:
def mount_householder_matrix_to_qr(A, j):
    A = A.astype(np.float32)
    n_A = len(A)
    v = np.zeros(n_A)
    w = np.zeros(n_A)
    v[j:] = A[j:,j]
    w[j] = np.linalg.norm(v)
    n = np.array([(v - w) / np.linalg.norm(v - w)])
    H = np.identity(n_A) - 2 * (n.T @ n)
    H = np.around(H, decimals=5)
    return H

In [4]:
def qr_decomposition(A):
    n_A = len(A)
    Q = np.identity(n_A)
    R = A.copy()
    
    for j in range(0, n_A - 1):
        Qj = mount_householder_matrix_to_qr(R, j)
        R = Qj @ R
        Q = Q @ Qj        
    return Q, R

### Teste com Matriz Simétrica 

In [5]:
# Matriz 3x3
A = np.array([[ 12, -51,  4],
               [  6, 167,-68],
               [ -4,  24,-41]])

Q, R = qr_decomposition(A)

In [6]:
print("Matriz Q (ortogonal):\n", Q)
print("\nMatriz R (triangular superior):\n", R)
print("\nMatriz A:\n", A)
print("\nMatriz produto QR = A:\n", Q @ R)

Matriz Q (ortogonal):
 [[ 0.85714   -0.3942812  0.3314284]
 [ 0.42857    0.9028532 -0.0342824]
 [-0.28571    0.171428   0.942854 ]]

Matriz R (triangular superior):
 [[ 1.39999400e+01  2.10000100e+01 -1.40000900e+01]
 [ 3.28000000e-05  1.74999098e+02 -6.99996904e+01]
 [ 3.04000000e-05  4.86800000e-04 -3.50000972e+01]]

Matriz A:
 [[ 12 -51   4]
 [  6 167 -68]
 [ -4  24 -41]]

Matriz produto QR = A:
 [[ 11.99990571 -50.99874429   3.99949857]
 [  5.99998286 166.99845286 -67.99957572]
 [ -3.99988857  24.00029143 -40.99992286]]


In [7]:
# Matriz 7x7
A = np.array([[ 3,-2, 1, 1,-2, 0, 2],
              [-2, 3, 0, 2, 1, 0, 0],
              [ 1, 0, 2, 0, 2, 1, 1],
              [ 1, 2, 0, 3, 0, 0, 2],
              [-2, 1, 2, 0, 3, 1, 0],
              [ 0, 0, 1, 0, 1, 1,-1],
              [ 2, 0, 1, 2, 0,-1, 1]])

Q, R = qr_decomposition(A)

In [8]:
print("Matriz Q (ortogonal):\n", Q)
print("\nMatriz R (triangular superior):\n", R)
print("\nMatriz A:\n", A)
print("\nMatriz produto QR = A:\n", Q @ R)

Matriz Q (ortogonal):
 [[ 6.25540000e-01 -1.26899708e-01  2.06721889e-01  5.12690093e-01
  -5.04513322e-01  1.09364439e-01  1.43217656e-01]
 [-4.17030000e-01  5.71037875e-01 -2.08203878e-06  2.53641112e-01
  -5.34974253e-01 -3.14357373e-01 -2.25049860e-01]
 [ 2.08510000e-01  1.52281063e-01  5.58151760e-01 -7.03989976e-01
  -2.73059129e-01 -1.91211496e-01  1.22752327e-01]
 [ 2.08510000e-01  7.36011063e-01 -1.44703671e-01 -4.60742303e-02
   1.66983175e-01  5.19313178e-01  3.06884872e-01]
 [-4.17030000e-01 -1.26821254e-02  7.02862063e-01  3.56600924e-01
   2.61921774e-01  1.23164489e-01  3.47810187e-01]
 [ 0.00000000e+00  0.00000000e+00  3.10090000e-01 -3.41506703e-02
  -9.97216917e-03  5.46017027e-01 -7.77451100e-01]
 [ 4.17030000e-01  3.04552125e-01  1.86050754e-01  2.16246490e-01
   5.36754442e-01 -5.19292446e-01 -3.06887457e-01]]

Matriz R (triangular superior):
 [[ 4.79582000e+00 -2.50218000e+00  6.25530000e-01  1.25107000e+00
  -2.50218000e+00 -6.25550000e-01  2.29364000e+00]
 [-1.4

### Teste com Matriz Não Simétrica 

In [9]:
# Matriz 7x7
A = np.array([[3, -2, 1,-1, 2, 0, 2],
              [1, 3, 0, 2, 1, 0, 0],
              [5, 0, 2, 0, 2, 1, 1],
              [1, 5, 0, 3, 0, 0, 2],
              [2, 1, 3, 5, 3, 1, 0],
              [3, 5, 1, 0, 2, 1, 1],
              [2, 0, 5, 2,-3, 0, 1]])

Q, R = qr_decomposition(A)

In [10]:
print("Matriz Q (ortogonal):\n", Q)
print("\nMatriz R (triangular superior):\n", R)
print("\nMatriz A:\n", A)
print("\nMatriz produto QR = A:\n", Q @ R)

Matriz Q (ortogonal):
 [[ 4.12080000e-01 -4.06679005e-01 -2.46266342e-01  4.86991875e-02
   5.18435075e-02 -7.27535914e-01  2.64146289e-01]
 [ 1.37360000e-01  3.49297378e-01 -7.82003307e-02  2.38809059e-01
  -1.43903597e-01 -3.74563738e-01 -7.96837879e-01]
 [ 6.86800000e-01 -2.37013010e-01 -2.65142745e-01  4.02076889e-02
  -2.95996933e-01  5.39298481e-01 -1.47488091e-01]
 [ 1.37360000e-01  6.13767378e-01 -3.55708658e-02  2.55054428e-01
  -5.21231801e-01 -8.86910492e-02  5.08478635e-01]
 [ 2.74720000e-01  3.74097716e-02  4.05291296e-01  6.98850576e-01
   4.99646164e-01  1.12642496e-01  9.02490116e-02]
 [ 4.12080000e-01  5.18959488e-01 -9.70750106e-02 -5.18630224e-01
   5.28389578e-01 -1.11243940e-04  5.72382358e-02]
 [ 2.74720000e-01 -9.48202284e-02  8.29450890e-01 -3.41411517e-01
  -2.97438343e-01 -1.37778439e-01 -5.94309211e-02]]

Matriz R (triangular superior):
 [[ 7.28008000e+00  2.60984000e+00  4.39552000e+00  2.19776000e+00
   3.15928000e+00  1.37360000e+00  2.47248000e+00]
 [ 2.0